name: Financer Tag and Release

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Cache NuGet packages
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore dependencies
        run: dotnet restore

      - name: Build Solution
        run: dotnet build --configuration Release --no-restore

      - name: Run Tests
        run: dotnet test --configuration Release --no-restore --verbosity normal

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}

      - name: Variable Substitution in appsettings.json
        uses: microsoft/variable-substitution@v1
        with:
          files: '**/appsettings.json'
        env:
          "Logging.Telegram.BotToken": "${{ secrets.TELEGRAM_BOT_TOKEN }}"
          "Logging.Telegram.ChatId": "${{ secrets.TELEGRAM_CHAT_ID }}"
          "YNAB.Pat": "${{ secrets.YNAB_ACCESS_TOKEN }}
          "YNAB.BudgetId": "${{ secrets.YNAB_BUDGET_ID }}"
          "Monobank.AccessToken": "${{ secrets.MONOBANK_TOKEN }}"


      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Financer.Api/Dockerfile
          push: true
          tags: ghcr.io/bardin08/financer:${{ steps.tag_version.outputs.new_version }}
